# Generated by Django 2.1.8 on 2020-07-04 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('header', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='CREATED', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogsmanagement.Article')),
            ],
            options={
                'verbose_name': 'comments',
                'verbose_name_plural': 'comments',
                'ordering': ('-createdAt',),
            },
        ),
    ]
